name: Docker publish image

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    container: golang:1.20.4

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Show go version
        run: go version

      - name: build
        run: go build -buildvcs=false

  push:
    runs-on: ubuntu-latest

    needs: build-test

    steps:
      - uses: actions/checkout@v3.5.3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gorm-user-auth:latest
          platforms: linux/amd64,linux/arm64